language: node_js
node_js:
  - "13"
  - "14"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g yarn
script:
  - echo "Running tests against $(node -v)"
  - yarn lint
  - yarn test-headless
  - yarn build

jobs:
  include:
    - stage: release
      node_js: "14"
      script: ./deploy.sh
stages:
  - test
  - name: release
    if: (NOT type IN (pull_request)) AND (branch = master)
